### ISSUE TITLE
Fails to load if plugin name is different from repository 

### ISSUE THREAD

**Issue by totoroot** [jandamm/zgenom#146] opened 2023-10-02 10:19 UTC
Not sure if that is actually something that should be handled, but for a couple of my plugins, zgenom complains about not being able to load them.

```sh
Cloning into '/home/.../.zgenom/sources/zdharma/history-search-multi-word/___'...
... done.
-- zgenom: Failed to load /home/.../.zgenom/sources/zdharma/history-search-multi-word/___ -- main
```

The reason is that these plugins do not have the same name as the repository.
For the given example the repository is named `history-search-multi-word` but the plugin itself is `H-S-MW.plugin.zsh`, which I suspect is the reason that zgenom cannot find and load it then.

I worked around this by forking the affected plugins and renaming the file to e.g. `history-search-multi-word.plugin.zsh` so they match the repo's name.

**Comment by jandamm** [comment] 2023-10-03 18:09
Hey @totoroot,

thank you for reporting that issue.

First of all if a repository doesn't include any matching files you don't have to create/rename files.
You can just provide the filename as second parameter to `load`.
```
zgenom load zdharma/history-search-multi-word H-S-MW.plugin.zsh
```
I once had an example in the readme but I removed it to reduce confusion. 🤷‍♂️

Secondly I tested the repo and the file should be matched.
I guess you have different `setopt` than I have and one affects globbing. Which then leads to not finding anything for `*.plugin.zsh`.

Could you please run `setopt` in your terminal and paste the output into this issue so I can verify my idea and hopefully fix it without requiring you to specify filenames manually?

**Comment by totoroot** [comment] 2023-10-17 11:21
Hi @jandamm and thanks for the prompt response! :)

Thanks for providing a solution to my issue. Unfortunately I didn't think of just providing the filename as a second parameter to `load`.
With the ability to specify the filename, I consider it resolved, so feel free to close the issue.

Thanks, it could indeed be due differences in globbing behaviour. Here's is my output of `setopt`:
```
autocd
autopushd
autoresume
nobeep
nobgnice
nocaseglob
cdablevars
nocheckjobs
combiningchars
completeinword
extendedglob
extendedhistory
histexpiredupsfirst
histfcntllock
histfindnodups
histignorealldups
histignoredups
histignorespace
histsavenodups
histverify
nohup
ignoreeof
incappendhistory
interactive
longlistjobs
monitor
nonomatch
pathdirs
promptsubst
pushdignoredups
pushdsilent
pushdtohome
rcquotes
sharehistory
shinstdin
zle
```

Thanks again!

**Comment by jandamm** [comment] 2023-10-28 21:08
@totoroot I tried a few things but I still haven't been able to reproduce this error.

In case your interested to test it, you'd find the code in `$ZGEN_SOURCE/functions/zgenom-load`.
It should match in line 112. So the issue is probably in `__zgenom_path_contains` in the same file.

I'm closing this issue for now. Feel free to reopen in case you found anything 😊

**Closed** 2023-10-28 21:08 UTC
