### ISSUE TITLE
Theme not loading after install or reset

### ISSUE THREAD

**Issue by Justkant** [jandamm/zgenom#101] opened 2021-12-23 01:28 UTC
Hi,

After migrating from zgen I had an issue with the latest version where the theme is not loaded when creating a zgenom save.

After some digging I found that the issue starts with https://github.com/jandamm/zgenom/pull/63

With https://github.com/jandamm/zgenom/commit/8ed1e264416b1615748e57498b8b7a4c96558f85 it is working correctly:
![zgenom_theme_working](https://user-images.githubusercontent.com/3009753/147173172-8ac481d7-482f-4c24-ae37-980c4b8e6df6.png)

But not with https://github.com/jandamm/zgenom/commit/dd433881a58cd3ca36c98366be190d1d70f80bf9:
![zgenom_theme_issue](https://user-images.githubusercontent.com/3009753/147173233-69009f04-51e4-4595-bfa4-47700b01040f.png)

<details>
  <summary><code>.zshrc</code> used for testing</summary>

```zsh
# zgen installation
# git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"

ZGEN_DIR="$HOME/.zgen"

# load zgenom
source "${HOME}/.zgenom/zgen.zsh"

# Check for plugin and zgenom updates every 7 days
# This does not increase the startup time.
# zgenom autoupdate

# enable error redirect from react-native app
export REACT_EDITOR="code"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/ssh-agent
    zgen oh-my-zsh plugins/docker
    zgen oh-my-zsh plugins/docker-compose
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/common-aliases
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/gitfast
    zgen oh-my-zsh plugins/node
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/yarn
    zgen oh-my-zsh plugins/emacs
    zgen oh-my-zsh plugins/kubectl
    zgen oh-my-zsh plugins/vscode
    zgen oh-my-zsh plugins/gcloud
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-autosuggestions

    # completions
    zgen load zsh-users/zsh-completions src
    zgen load lukechilds/zsh-better-npm-completion

    # theme
    zgen oh-my-zsh themes/clean

    # save all to init script
    zgen save

    # Compile your zsh files
    #zgen compile "$HOME/.zshrc"
fi

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
```
</details>

<details>
  <summary>current <code>.zshrc</code></summary>

```zsh
# zgenom installation
# git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"

# load zgenom
source "${HOME}/.zgenom/zgenom.zsh"

# Check for plugin and zgenom updates every 7 days
# This does not increase the startup time.
zgenom autoupdate

# enable error redirect from react-native app
export REACT_EDITOR="code"

# check if there's no init script
if ! zgenom saved; then
    echo "Creating a zgenom save"

    zgenom ohmyzsh

    # plugins
    zgenom ohmyzsh plugins/ssh-agent
    zgenom ohmyzsh plugins/docker
    zgenom ohmyzsh plugins/docker-compose
    zgenom ohmyzsh plugins/sudo
    zgenom ohmyzsh plugins/common-aliases
    zgenom ohmyzsh plugins/command-not-found
    zgenom ohmyzsh plugins/git
    zgenom ohmyzsh plugins/gitfast
    zgenom ohmyzsh plugins/node
    zgenom ohmyzsh plugins/npm
    zgenom ohmyzsh plugins/yarn
    zgenom ohmyzsh plugins/emacs
    zgenom ohmyzsh plugins/kubectl
    zgenom ohmyzsh plugins/vscode
    zgenom ohmyzsh plugins/gcloud
    zgenom load zsh-users/zsh-syntax-highlighting
    zgenom load zsh-users/zsh-autosuggestions

    # completions
    zgenom load zsh-users/zsh-completions src
    zgenom load lukechilds/zsh-better-npm-completion

    # theme
    zgenom ohmyzsh themes/clean

    # save all to init script
    zgenom save

    # Compile your zsh files
    zgenom compile "$HOME/.zshrc"
fi

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
```
</details>

**Comment by jandamm** [comment] 2021-12-23 20:35
Hi @Justkant,

thanks for reporting and bisecting the issue 👍

This seems to be an issue with [Prompt Expansion](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html).
Unfortunately I don't know yet what caused the prompt expansion to change in #63.
I probably won't be able to have a look before/while Christmas.

**Comment by Justkant** [comment] 2021-12-23 21:05
> I probably won't be able to have a look before/while Christmas.

No problem, it can wait.

**Comment by jandamm** [comment] 2021-12-24 11:57
I just had a quick look and I can reproduce it.

The prompt looks wrong in the shell when `reset` has been executed before. In the following shells it looks fine for me.

It's definitely the `setopt promptsubst` which should have been set by `zgenom ohmyzsh` but now isn't set anymore.

My guess is that `localoptions` is set before sourcing the files. Which might result in the options not being set for the shell.

In the meantime you should be able to fix this by adding `setopt promptsubst` before the `zgenom saved` part.

**Comment by jandamm** [comment] 2021-12-25 12:05
Wow, this is really an edge case.

For the first call* of `zgenom` `localoptions` is set but for none of the following.
So since your first call is `zgenom ohmyzsh` none of the options set by `oh-my-zsh.sh` are applied to the current shell (including `prompsubst`).

If you'd have any call to zgenom before the ohmyzsh one this issue wouldn't have occurred.

\* `saved`/`autoupdate` don't count since they're not lazy loaded.

**Comment by jandamm** [comment] 2021-12-27 14:28
Hey @Justkant should be fixed now 👍

**Closed** 2021-12-27 14:27 UTC
Labels: bug
